global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: login-validator
    metrics_path: /metrics
    static_configs:
      - targets:
          - login-validator:2112
